# Generated by Django 3.1.3 on 2020-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=200)),
                ('adult', models.BooleanField(default=False)),
                ('overview', models.TextField()),
                ('vote_count', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('admin_reg', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
